#!/usr/bin/env bash
# Generated by @voxgig/sdkgen. Registers this repository's npm publish
# workflows as trusted publishers; --check reports drift, --dry-run changes nothing.
set -euo pipefail
sdk_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
trust="$sdk_dir/node_modules/@voxgig/sdkgen/dist/admin/npm-trust.js"
if [[ ! -f "$trust" ]]; then
  echo 'Install or update the .sdk dependencies to configure npm trusted publishing.' >&2
  exit 1
fi
exec node "$trust" \
  --repository 'voxgig-sdk/postmark-sdk' \
  --publish '@voxgig-sdk/postmark-sdk=publish-ts.yml' \
  "$@"
